services:

  postgres:

    image: postgres:13-alpine
    container_name: postgres_db

    env_file:
      - ./.env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network  # ✅ 외부 네트워크 사용
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  creator:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: table_creator

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - ./.env

    networks:
      - app_network  # ✅ 외부 네트워크 사용
    restart: "no"

volumes:
  pgdata:

networks:
  app_network:
    external: true  # ✅ 외부 네트워크 사용 설정
